name: diffusionmagic-env
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
      - accelerate==0.16.0
      - diffusers==0.13.1
      - gradio==3.17.1
      - safetensors==0.2.8
      - scipy==1.10.0
      - transformers==4.26.0
      - pydantic==1.10.4
      - mypy==1.0.0
      - black==23.1.0
      - flake8==6.0.0